name: miniproject
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI & Icons
  cupertino_icons: ^1.0.8

  # Firebase Suite (Upgraded to v3-compatible versions)
  firebase_core: ^4.1.0
  firebase_auth: ^6.0.2
  cloud_firestore: ^6.0.1
  firebase_database: ^12.0.1
  firebase_messaging: ^16.0.1
  firebase_ai: ^3.2.0

  # Location & Mapping
  flutter_map: ^8.2.1
  latlong2: ^0.9.1
  geolocator: ^14.0.2
  geocoding: ^4.0.0

  # Utilities
  shared_preferences: ^2.2.3
  image_picker: ^1.1.2
  cloudinary_public: ^0.23.1
  firebase_vertexai: ^2.2.0
  image_cropper: ^9.1.0
  url_launcher: ^6.3.2
  
  flutter_local_notifications: ^17.1.2
  http: ^1.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
